apiVersion: v1
kind: Service
metadata:
  name: nodeport
  labels:
    run: wordpress-deployment
    app: frontend
spec:
  ports:
  - port: 80
  selector:
    app: frontend
    run: wordpress-deployment
  type: NodePort
