apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: wordpress-deployment
    app: frontend
  name: {{.Values.deployment.name}}
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: wordpress-deployment
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: wordpress-deployment
        app: frontend
    spec:
      containers:
      - image: {{.Values.containers.image}}
        name: {{.Values.containers.name}}
